
version: "3.7"
services:
    web:
        build: .
        ports:
            - "8188:80"
        depends_on:
            - db
        volumes: 
            - "/var/log:/var/log/"
    db:
        image: "mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "Abc_123@johnhu"
        ports:
            - "3306:3306"
        volumes:
            - "/var/lib/mysql/:/var/lib/mysql/"
            
            